// <auto-generated />
namespace GuoGuoCommunity.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatevipOwnerApplicationRecord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatevipOwnerApplicationRecord));
        
        string IMigrationMetadata.Id
        {
            get { return "201903300243287_update-vipOwnerApplicationRecord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
