// <auto-generated />
namespace GuoGuoCommunity.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateshop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateshop));
        
        string IMigrationMetadata.Id
        {
            get { return "201905210129201_update-shop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
