// <auto-generated />
namespace GuoGuoCommunity.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateComplaint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateComplaint));
        
        string IMigrationMetadata.Id
        {
            get { return "201904020758058_update-Complaint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
